# Conversation states
MAIN_MENU = 0
LOGIN_USERNAME = 1
LOGIN_PASSWORD = 2
REGISTER_USERNAME = 3
REGISTER_PASSWORD = 4
REGISTER_EMAIL = 5
REGISTER_SEX = 6
TRACK_PERIOD_START = 7
TRACK_PERIOD_END = 8
TRACK_PERIOD_SYMPTOMS = 9
TRACK_PERIOD_MEDICATION = 10
DASHBOARD = 11
PROFILE_VIEW = 12
PARTNER_INVITATION = 13
PARTNER_ACCEPT = 14
CYCLE_ANALYSIS = 15
# User data keys
USERNAME = "username"
PASSWORD = "password"
EMAIL = "email"
SEX = "sex"
TOKEN = "token"
USER_ID = "user_id"
CURRENT_PERIOD = "current_period"

# API URLs (configure in config.py)
BASE_URL = "BASE_URL_FROM_CONFIG"

# Add to existing constants
PROFILE_VIEW = 16
PARTNER_MENU = 17
GENERATE_INVITATION = 18
ACCEPT_INVITATION = 19
REMOVE_PARTNER = 20
START = 21
START_LOGIN = 22
START_REGISTER = 23
ACCEPT_REMOVE_CODE = 24
SETTINGS = 25

EDIT_FIRST_NAME =26
EDIT_LAST_NAME = 27
EDIT_CYCLE_LENGTH = 28
EDIT_PERIOD_DURATION = 29
START_DELETE=30
CONFIRM_DELETE=31