# Define all conversation states
REGISTER = 0
LOGIN = 1
PERIOD_TRACKING = 2
MENU = 3
ACCEPTING_INVITATION = 4
SETTINGS = 5
START_DATE = 6
SYMPTOMS = 7
MEDICATION = 8
PARTNER_MENU = 11
PARTNER_MESSAGE = 12

# Export all states
__all__ = [
    'REGISTER', 'LOGIN', 'PERIOD_TRACKING', 'MENU',
    'ACCEPTING_INVITATION', 'SETTINGS', 'START_DATE',
    'SYMPTOMS', 'MEDICATION', 'PARTNER_MENU',
    'PARTNER_MESSAGE'
] 