# states.py
# Main states
MENU = 0
REGISTER = 1
LOGIN = 2
PASSWORD = 3
ADD_CYCLE_DATE = 4
START_DATE = 5
SYMPTOMS = 6
MEDICATION = 7
CYCLE_LENGTH = 8
PERIOD_DURATION = 9
HISTORY = 10
ANALYSIS = 11
SETTINGS = 12
PARTNER_MENU = 13
PARTNER_ADD = 14
PARTNER_VIEW = 15
PARTNER_REMOVE = 16
PARTNER_REQUEST = 17
PARTNER_RESPOND = 18

# Settings states
SETTINGS_MENU = 100
LANGUAGE_SELECTION = 101
PROFILE_MENU = 102
ViewProfile = 103


# Cycle Analysis states
CYCLE_ANALYSIS_MENU = 200

#   Partner states
ACCEPT_INVITE_CODE = 300
VIEW_PARTNERS = 301
REMOVE_PARTNER = 302
GET_INVITE_CODE = 303
ACCEPT_REMOVE_CODE=304
SEND_MESSAGE = 305
