# Define all conversation states
REGISTER = 0
LOGIN = 1
PERIOD_TRACKING = 2
MENU = 3
ACCEPTING_INVITATION = 4
SETTINGS = 5
START_DATE, END_DATE, SYMPTOMS, MEDICATION = range(6, 10)

# Export all states
__all__ = [
    'REGISTER', 'LOGIN', 'PERIOD_TRACKING', 'MENU',
    'ACCEPTING_INVITATION', 'SETTINGS', 'START_DATE',
    'END_DATE', 'SYMPTOMS', 'MEDICATION'
] 