# ========== HANDLE FEEDBACK ==========
from venv import logger
import aiohttp
from telegram import InlineKeyboardButton, InlineKeyboardMarkup, ReplyKeyboardMarkup, Update
from telegram.ext import ContextTypes, ConversationHandler
from utils.token_store import get_token
from constants import DASHBOARD, FEEDBACK_REASON, FEEDBACK_TEXT
from modules.ai.api import send_feedback_to_api
FEEDBACK_REASONS = [
    ("Wrong Timing (e.g., predicted period, got fertile)", "timing"),
    ("Advice Not Relevant (e.g., suggested rest, needed exercise)", "advice"),
    ("Missing Info (e.g., didn't mention high pain)", "missing_info"),
    ("Other / Free Text", "other")
]

async def feedback_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    print("In feedback_handler")
    query = update.callback_query
    await query.answer()

    _, suggestion_id, feedback_value = query.data.split(":")

    chat_id = update.effective_chat.id
    token = context.user_data.get("token") or get_token(chat_id)



    if not token:
        await query.edit_message_text("⚠️ You are not logged in!")
        return

    if feedback_value == "true":
        
        result = await send_feedback_to_api(suggestion_id, token, True)
        print(result)
        if result and result.get("status") == "success":
            await query.edit_message_text("✅ Thanks for your feedback!")
            
            return DASHBOARD
        else:
            await query.edit_message_text("❌ Failed to send feedback. Please try again later.")
        return DASHBOARD
    else:
        # User indicated the suggestion was not helpful. Initiate structured feedback.
        print("User indicated the suggestion was not helpful. Starting structured feedback.")
        
        # 1. Store the suggestion ID and the current state to user_data
        context.user_data["pending_feedback_id"] = suggestion_id
        
        # 2. EDIT the ORIGINAL MESSAGE to remove the inline keyboard and ask the reason.
        await query.edit_message_text(
            "❌ Sorry it wasn't helpful. Please select the primary reason why the suggestion was incorrect:",
            reply_markup=InlineKeyboardMarkup([
                [InlineKeyboardButton(label, callback_data=f"reason:{suggestion_id}:{key}")]
                for label, key in FEEDBACK_REASONS
            ])
        )

        # Transition to the new state to handle the reason selection
        return FEEDBACK_REASON


async def reason_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handles the user's selection of why the suggestion was incorrect."""
    query = update.callback_query
    await query.answer()

    # data format: "reason:{suggestion_id}:{reason_key}"
    _, suggestion_id, reason_key = query.data.split(":")
    
    # Pre-defined list of all possible primary labels for selection
    # NOTE: You should ensure this list covers all labels generated by generate_synthetic_dataset.py
    ALL_LABELS = [
        "Period is today: prioritize rest & hydration",
        "PMS: focus on relaxation and comfort",
        "Pre-period phase: prepare for menstruation",
        "Ovulation day: track symptoms closely",
        "Fertile window: track symptoms & take care",
        "Unusually short cycle: monitor closely",
        "Unusually long cycle: consult if recurring",
        "Unusually long period: consult doctor",
        "Severe symptoms/stress: rest & consult",
        "Rest & Take medication",
        "Lack of sleep: prioritize rest",
        "Take medication",
        "Balanced nutrition",
        "Exercise lightly",
        "Hydrate & Rest",
        "Mindfulness recommended",
        "Severe stress/symptoms: rest & consult",
        "Moderate symptoms: monitor & hydrate",
        "Poor sleep: get more rest",
        "High stress: relax & hydrate",
        "Stay active",
        "Get enough sleep",
        "Hydrate & Relax",
        "Severe pain: consult doctor",
        "High anxiety: relaxation or mindfulness recommended",
        "Low mood & low energy: light activity recommended",
        "High stress + poor sleep: try mindfulness & rest",
    ]
    
    context.user_data["feedback_reason"] = reason_key
    
    if reason_key == "other":
        # If 'Other' is selected, skip phase selection and go straight to free text input
        # We re-use the old text input handler (text_feedback_handler)
        
        # 1. EDIT the ORIGINAL MESSAGE to remove the inline keyboard
        await query.edit_message_text(
            "Please type your specific correction or note in a **new message**.",
            reply_markup=None 
        )

        # 2. SEND A NEW MESSAGE with the ReplyKeyboardMarkup for text input.
        keyboard = [["⬅️ Back to Dashboard"]]
        reply_markup = ReplyKeyboardMarkup(keyboard, resize_keyboard=True, one_time_keyboard=True)
        
        await context.bot.send_message(
            chat_id=query.message.chat_id,
            text="Type your feedback (e.g., 'I was actually ovulating') or tap the button to go back:",
            reply_markup=reply_markup
        )

        return FEEDBACK_TEXT
        
    else:
        # For 'timing', 'advice', or 'missing_info', ask for the correct label from the list
        
        # Organize labels into two columns for better visibility
        mid_point = len(ALL_LABELS) // 2
        keyboard_rows = []
        for i in range(mid_point):
            row = [InlineKeyboardButton(ALL_LABELS[i], callback_data=f"label:{suggestion_id}:{ALL_LABELS[i]}")]
            if i + mid_point < len(ALL_LABELS):
                row.append(InlineKeyboardButton(ALL_LABELS[i+mid_point], callback_data=f"label:{suggestion_id}:{ALL_LABELS[i+mid_point]}"))
            keyboard_rows.append(row)
        
        # Add any remaining single label
        if len(ALL_LABELS) % 2 != 0:
             keyboard_rows.append([InlineKeyboardButton(ALL_LABELS[-1], callback_data=f"label:{suggestion_id}:{ALL_LABELS[-1]}")])

        
        await query.edit_message_text(
            f"You selected '{reason_key}'. Now, please select the **CORRECT** primary suggestion label below:",
            reply_markup=InlineKeyboardMarkup(keyboard_rows)
        )
        # We remain in FEEDBACK_REASON state to handle the label selection next
        return FEEDBACK_REASON


async def label_selection_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handles the user's selection of the correct primary label."""
    query = update.callback_query
    await query.answer()
    
    # data format: "label:{suggestion_id}:{corrected_label}"
    data = query.data.split(":")
    suggestion_id = data[1]
    # The label can contain spaces and colons, so we must reconstruct it correctly.
    corrected_label = ":".join(data[2:])
    
    chat_id = update.effective_chat.id
    token = context.user_data.get("token") or get_token(chat_id)
    
    if not token:
        await query.edit_message_text("⚠️ You are not logged in!")
        return DASHBOARD
    
    # Send structured feedback (corrected_label is the main payload)
    result = await send_feedback_to_api(
        suggestion_id=suggestion_id, 
        token=token, 
        feedback=False, # Negative feedback
        corrected_label=corrected_label, 
        # response_text=context.user_data.get("feedback_reason", "") 
    )
    print ("resulat is:" , result)
    if result and result.get("status") == "success":
        await query.edit_message_text(f"🙏 Thanks! Feedback logged as: **{corrected_label}**.")
    else:
        await query.edit_message_text("❌ Failed to send feedback. Please try again later.")

    context.user_data.pop("pending_feedback_id", None)
    context.user_data.pop("feedback_reason", None)
    return DASHBOARD


async def text_feedback_handler(update, context):
    print("In text_feedback_handler")
    suggestion_id = context.user_data.get("pending_feedback_id")
    if not suggestion_id:
        return DASHBOARD  

    text = update.message.text

    keyboard = [["⬅️ Back to Dashboard"]]
    reply_markup = ReplyKeyboardMarkup(keyboard, resize_keyboard=True)

    if text == "⬅️ Back to Dashboard":
        context.user_data.pop("pending_feedback_id", None)
        context.user_data.pop("feedback_reason", None)
        from modules.users.handlers import show_dashboard
        return await show_dashboard(update, context)

    corrected_label = "User supplied text feedback" # Use a generic label for free text input
    response_text = text # Store the actual text in response_text column
    token = context.user_data.get("token") or get_token(update.effective_chat.id)

    result = await send_feedback_to_api(
        suggestion_id=suggestion_id, 
        token=token, 
        feedback=False, 
        corrected_label=corrected_label, 
        response_text=response_text
    )
    print("==========>>",result)
    
    if result and result.get("status") == "success":
        await update.message.reply_text(
            "🙏 Thanks, your feedback will help improve the AI!",
            reply_markup=ReplyKeyboardMarkup([["⬅️ Back to Dashboard"]], resize_keyboard=True)
        )
    else:
        await update.message.reply_text(
            "❌ Failed to send feedback to the API. Please try again later.",
            reply_markup=ReplyKeyboardMarkup([["⬅️ Back to Dashboard"]], resize_keyboard=True)
        )

    context.user_data.pop("pending_feedback_id", None)
    context.user_data.pop("feedback_reason", None)
    
    return DASHBOARD
